enum DocumentEvents {
  DOCUMENT_ACTIVE,
  DOCUMENT_CHANGE,
  DOCUMENT_CLOSE,
  DOCUMENT_CREATE,
  DOCUMENT_DELETE,
  DOCUMENT_FOLD_DOWN,
  DOCUMENT_FOLD_UP,
  DOCUMENT_GROUP,
  DOCUMENT_OPEN,
  DOCUMENT_RENAME,
  DOCUMENT_SAVE,
  DOCUMENT_SELECTION,
  DOCUMENT_UNGROUP,
  DOCUMENT_VIEW_COLUMN,
  DOCUMENT_VISIBLE,
  DOCUMENT_VISIBLE_RANGE,
}

export { DocumentEvents };
