const CODIO_EDITOR_CHANGED = 'editor';
const CODIO_SELECTION_CHANGED = 'selection';
const CODIO_VISIBLE_RANGE_CHANGED = 'visibleRange';
const CODIO_EXEC = 'exec';

enum DocumentEvents {
  DOCUMENT_CHANGE,
  DOCUMENT_CLOSE,
  DOCUMENT_CREATE,
  DOCUMENT_DELETE,
  DOCUMENT_OPEN,
  DOCUMENT_RENAME,
  DOCUMENT_SAVE,
  DOCUMENT_SELECTION,
  DOCUMENT_SCROLL,
}

export { CODIO_EDITOR_CHANGED, CODIO_SELECTION_CHANGED, CODIO_VISIBLE_RANGE_CHANGED, CODIO_EXEC, DocumentEvents };
